version: '3'

services:
  db:
      image: postgres:alpine
      restart: always
      container_name: "postgres-hubla"
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432
  app:
    build: .
    container_name: "api-hubla"
    command: sh -c "npm run prisma:migrate && npm run start:dev"
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db
networks:
  overlay:
volumes:
  postgres:
